name: shadcn-init-button
description: Instala Tailwind se necessário e adiciona o componente "button" do shadcn/ui
actions:
  - type: detect-package-manager

  # Se Tailwind não estiver configurado, instala e inicializa
  - type: detect-file
    path: tailwind.config.js
    notFoundActions:
      - type: install
        dev: true
        packages:
          - tailwindcss
          - postcss
          - autoprefixer

      - type: run
        command: npx tailwindcss init -p

      - type: merge-file
        target: tailwind.config.js
        content: |
          /** @type {import('tailwindcss').Config} */
          module.exports = {
            content: [
              "./src/**/*.{js,ts,jsx,tsx}",
              "./components/**/*.{js,ts,jsx,tsx}"
            ],
            theme: {
              extend: {},
            },
            plugins: [],
          }

      - type: merge-file
        target: src/globals.css
        content: |
          @tailwind base;
          @tailwind components;
          @tailwind utilities;

  # Instala dependências do shadcn/ui
  - type: install
    dev: true
    packages:
      - class-variance-authority
      - tailwind-variants
      - prettier
      - prettier-plugin-tailwindcss

  - type: install
    dev: false
    packages:
      - lucide-react
      - react
      - react-dom
      - @radix-ui/react-slot
      - @radix-ui/react-icons

  # Garante pastas básicas
  - type: mkdir
    dirs:
      - src/components
      - src/pages

  # Inicializa e adiciona o componente Button
  - type: run
    command: npx shadcn@latest init

  - type: run
    command: npx shadcn@latest add button

  # Exemplo de uso
  - type: merge-file
    target: src/index.tsx
    content: |
      import "./globals.css";
      import { Button } from "@/components/ui/button";

      export default function App() {
        return (
          <div className="p-4">
            <Button>Botão funcionando</Button>
          </div>
        );
      }
