name: react-shadcn
description: Adiciona componentes ShadCN a um projeto React com Tailwind CSS
actions:
  - type: detect-package-manager

  # Verificar e instalar dependências necessárias
  - type: install
    dev: true
    packages:
      - tailwindcss
      - postcss
      - autoprefixer

  # Verificar se tailwind.config.js existe
  - type: detect-file
    path: tailwind.config.js
    notFoundActions:
      - type: run
        command: npx tailwindcss init -p
      
      - type: merge-file
        target: tailwind.config.js
        content: |
          /** @type {import('tailwindcss').Config} */
          module.exports = {
            content: [
              "./app/**/*.{js,ts,jsx,tsx,mdx}",
              "./pages/**/*.{js,ts,jsx,tsx,mdx}",
              "./components/**/*.{js,ts,jsx,tsx,mdx}",
              "./src/**/*.{js,ts,jsx,tsx,mdx}",
            ],
            theme: {
              extend: {},
            },
            plugins: [],
          }

  # Verificar se globals.css existe e tem as diretivas Tailwind
  - type: detect-file
    path: src/globals.css
    notFoundActions:
      - type: merge-file
        target: src/globals.css
        content: |
          @tailwind base;
          @tailwind components;
          @tailwind utilities;

  # Verificar versão do React para determinar flags necessárias
  - type: detect-file
    path: package.json
    notFoundActions:
      - type: run
        command: echo "Arquivo package.json não encontrado. Não é possível determinar a versão do React."
  
  # Verificar se components.json existe
  - type: detect-file
    path: components.json
    notFoundActions:
      - type: install
        packages:
          - class-variance-authority
          - clsx
          - tailwind-merge
          - lucide-react
      
      - type: merge-file
        target: components.json
        content: |
          {
            "$schema": "https://ui.shadcn.com/schema.json",
            "style": "default",
            "rsc": false,
            "tailwind": {
              "config": "tailwind.config.js",
              "css": "src/globals.css",
              "baseColor": "slate",
              "cssVariables": false
            },
            "aliases": {
              "components": "@/components",
              "utils": "@/lib/utils"
            }
          }
      
      - type: mkdir
        dirs:
          - src/components/ui
          - src/lib
      
      - type: merge-file
        target: src/lib/utils.ts
        content: |
          import { type ClassValue, clsx } from "clsx"
          import { twMerge } from "tailwind-merge"
          
          export function cn(...inputs: ClassValue[]) {
            return twMerge(clsx(inputs))
          }

  # Instalação de todos os componentes Shadcn de uma só vez
  - type: run
    command: |
      echo "🔍 Verificando a versão do React no package.json..."
      
      # Lista de componentes para instalar
      SHADCN_COMPONENTS="accordion alert-dialog alert badge button card checkbox dialog dropdown-menu input label menubar navigation-menu popover progress radio-group scroll-area select separator skeleton slider switch table tabs textarea sonner toggle tooltip"
      
      # Verificar se estamos usando React 19
      if grep -q "\"react\": \"^19" package.json || grep -q "\"react\": \"19" package.json; then
        echo "⚠️ Detectado React 19. Usando --legacy-peer-deps para compatibilidade."
        echo "📦 Instalando todos os componentes Shadcn UI com --legacy-peer-deps..."
        npm --legacy-peer-deps exec -- shadcn@latest add $SHADCN_COMPONENTS
      else
        echo "📦 Instalando todos os componentes Shadcn UI..."
        npx shadcn@latest add $SHADCN_COMPONENTS 
