name: react-shadcn
description: Adiciona componentes ShadCN a um projeto React com Tailwind CSS
actions:
  - type: detect-package-manager

  # Verificar e instalar dependências necessárias
  - type: install
    dev: true
    packages:
      - tailwindcss
      - postcss
      - autoprefixer

  # Verificar se tailwind.config.js existe
  - type: detect-file
    path: tailwind.config.js
    notFoundActions:
      - type: run
        command: npx tailwindcss init -p
      
      - type: merge-file
        target: tailwind.config.js
        content: |
          /** @type {import('tailwindcss').Config} */
          module.exports = {
            content: [
              "./app/**/*.{js,ts,jsx,tsx,mdx}",
              "./pages/**/*.{js,ts,jsx,tsx,mdx}",
              "./components/**/*.{js,ts,jsx,tsx,mdx}",
              "./src/**/*.{js,ts,jsx,tsx,mdx}",
            ],
            theme: {
              extend: {},
            },
            plugins: [],
          }

  # Verificar se globals.css existe e tem as diretivas Tailwind
  - type: detect-file
    path: src/globals.css
    notFoundActions:
      - type: merge-file
        target: src/globals.css
        content: |
          @tailwind base;
          @tailwind components;
          @tailwind utilities;

  # Verificar se components.json existe
  - type: detect-file
    path: components.json
    notFoundActions:
      - type: install
        packages:
          - class-variance-authority
          - clsx
          - tailwind-merge
          - lucide-react
      
      - type: merge-file
        target: components.json
        content: |
          {
            "$schema": "https://ui.shadcn.com/schema.json",
            "style": "default",
            "rsc": false,
            "tailwind": {
              "config": "tailwind.config.js",
              "css": "src/globals.css",
              "baseColor": "slate",
              "cssVariables": false
            },
            "aliases": {
              "components": "@/components",
              "utils": "@/lib/utils"
            }
          }
      
      - type: mkdir
        dirs:
          - src/components/ui
          - src/lib
      
      - type: merge-file
        target: src/lib/utils.ts
        content: |
          import { type ClassValue, clsx } from "clsx"
          import { twMerge } from "tailwind-merge"
          
          export function cn(...inputs: ClassValue[]) {
            return twMerge(clsx(inputs))
          }

  # Verificar se estamos usando React 19
  - type: run
    command: node -e "const fs = require('fs'); try { const pkg = JSON.parse(fs.readFileSync('./package.json')); const isReact19 = pkg.dependencies && pkg.dependencies.react && pkg.dependencies.react.startsWith('19'); console.log(isReact19 ? 'REACT19=true' : 'REACT19=false'); fs.writeFileSync('./.react-version', isReact19 ? 'true' : 'false'); } catch(e) { console.log('REACT19=false'); fs.writeFileSync('./.react-version', 'false'); }"

  # Instalação dos componentes Shadcn UI - Para React 19
  - type: run
    command: node -e "const fs = require('fs'); if (fs.readFileSync('./.react-version', 'utf-8').trim() === 'true') { console.log('⚠️ Detectado React 19. Usando --legacy-peer-deps para compatibilidade.'); } else { process.exit(1); }"
    
  - type: run
    command: npm --legacy-peer-deps exec -- shadcn@latest add accordion alert-dialog alert badge button card checkbox dialog dropdown-menu input label menubar navigation-menu popover progress radio-group scroll-area select separator skeleton slider switch table tabs textarea sonner toggle tooltip

  # Instalação dos componentes Shadcn UI - Para React <19
  - type: run
    command: node -e "const fs = require('fs'); if (fs.readFileSync('./.react-version', 'utf-8').trim() === 'false') { console.log('✅ Instalando componentes para versão padrão do React'); } else { process.exit(1); }"
    
  - type: run
    command: npx shadcn@latest add accordion alert-dialog alert badge button card checkbox dialog dropdown-menu input label menubar navigation-menu popover progress radio-group scroll-area select separator skeleton slider switch table tabs textarea sonner toggle tooltip

  # Limpeza do arquivo temporário
  - type: run
    command: node -e "const fs = require('fs'); try { fs.unlinkSync('./.react-version'); } catch(e) {}" 
