name: react-shadcn
description: Adiciona componentes ShadCN a um projeto React com Tailwind CSS
actions:
  - type: detect-package-manager

  # Verificar e instalar dependências necessárias
  - type: install
    dev: true
    packages:
      - tailwindcss
      - postcss
      - autoprefixer

  # Verificar se tailwind.config.js existe
  - type: detect-file
    path: tailwind.config.js
    notFoundActions:
      - type: run
        command: npx tailwindcss init -p
      
      - type: merge-file
        target: tailwind.config.js
        content: |
          /** @type {import('tailwindcss').Config} */
          module.exports = {
            content: [
              "./app/**/*.{js,ts,jsx,tsx,mdx}",
              "./pages/**/*.{js,ts,jsx,tsx,mdx}",
              "./components/**/*.{js,ts,jsx,tsx,mdx}",
              "./src/**/*.{js,ts,jsx,tsx,mdx}",
            ],
            theme: {
              extend: {},
            },
            plugins: [],
          }

  # Verificar se globals.css existe e tem as diretivas Tailwind
  - type: detect-file
    path: src/globals.css
    notFoundActions:
      - type: merge-file
        target: src/globals.css
        content: |
          @tailwind base;
          @tailwind components;
          @tailwind utilities;

  # Verificar se components.json existe
  - type: detect-file
    path: components.json
    notFoundActions:
      - type: install
        packages:
          - class-variance-authority
          - clsx
          - tailwind-merge
          - lucide-react
      
      - type: merge-file
        target: components.json
        content: |
          {
            "$schema": "https://ui.shadcn.com/schema.json",
            "style": "default",
            "rsc": false,
            "tailwind": {
              "config": "tailwind.config.js",
              "css": "src/globals.css",
              "baseColor": "slate",
              "cssVariables": false
            },
            "aliases": {
              "components": "@/components",
              "utils": "@/lib/utils"
            }
          }
      
      - type: mkdir
        dirs:
          - src/components/ui
          - src/lib
      
      - type: merge-file
        target: src/lib/utils.ts
        content: |
          import { type ClassValue, clsx } from "clsx"
          import { twMerge } from "tailwind-merge"
          
          export function cn(...inputs: ClassValue[]) {
            return twMerge(clsx(inputs))
          }

  # Detectar React 19 com comando simples
  - type: run
    command: npx shadcn@latest add button

  # Instalar todos os componentes (vai detectar React 19 automaticamente)
  - type: run
    command: |
      npx shadcn@latest add accordion alert-dialog alert badge card checkbox dialog dropdown-menu input label menubar navigation-menu popover progress radio-group scroll-area select separator skeleton slider switch table tabs textarea sonner toggle tooltip 
