name: shadcn-all-components
description: Instala todos os componentes do shadcn/ui e configura Tailwind CSS se necessário
actions:
  - type: detect-package-manager

  - type: detect-file
    path: tailwind.config.js
    notFoundActions:
      - type: install
        dev: true
        packages:
          - tailwindcss
          - postcss
          - autoprefixer

      - type: run
        command: npx tailwindcss init -p

      - type: merge-file
        target: tailwind.config.js
        content: |
          /** @type {import('tailwindcss').Config} */
          module.exports = {
            content: [
              "./src/**/*.{js,ts,jsx,tsx}",
              "./components/**/*.{js,ts,jsx,tsx}"
            ],
            theme: {
              extend: {},
            },
            plugins: [require("@tailwindcss/forms")],
          }

      - type: merge-file
        target: src/globals.css
        content: |
          @tailwind base;
          @tailwind components;
          @tailwind utilities;

  - type: install
    dev: true
    packages:
      - class-variance-authority
      - tailwind-variants
      - lucide-react
      - @tailwindcss/forms
      - prettier
      - prettier-plugin-tailwindcss

  - type: install
    dev: false
    packages:
      - react
      - react-dom
      - @radix-ui/react-slot
      - @radix-ui/react-icons

  - type: mkdir
    dirs:
      - src/components
      - src/pages

  - type: run
    command: npx shadcn@latest init

  - type: run
    command: |
      npx shadcn@latest add accordion alert-dialog alert badge button card
      checkbox dialog dropdown-menu input label menubar
      navigation-menu popover progress radio-group scroll-area
      select separator skeleton slider switch table tabs
      textarea toast toggle tooltip

  - type: merge-file
    target: src/index.tsx
    content: |
      import "./globals.css";
      import { Button } from "@/components/ui/button";

      export default function App() {
        return (
          <div className="p-4">
            <Button>shadcn/ui funcionando</Button>
          </div>
        );
      }
